# https://github.com/actualbudget/actual/blob/master/packages/sync-server/docker-compose.yml
services:
  actual_server:
    image: 'actualbudget/actual-server:latest-alpine'
    environment:
      - SERVICE_URL_ACTUAL_5006
      - ACTUAL_LOGIN_METHOD=password
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=25
    volumes:
      - 'actual_data:/data'
    healthcheck:
      test:
        - CMD-SHELL
        - "bash -c ':> /dev/tcp/127.0.0.1/5006' || exit 1"
      interval: 5s
      timeout: 20s
      retries: 3
