services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    pull_policy: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/v1/status"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s

  warp:
    image: caomingjun/warp:latest
    container_name: warp
    restart: unless-stopped
    device_cgroup_rules:
      - "c 10:200 rwm"
    expose:
      - "1080"
    environment:
      - WARP_SLEEP=5
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./warp:/var/lib/cloudflare-warp
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -x 'socks5h://127.0.0.1:1080' -fsSL 'https://www.cloudflare.com/cdn-cgi/trace' | grep -qE 'warp=(plus|on)' || exit 1",
        ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 5s

  stremthru-proxy:
    image: ghcr.io/dydhzo/stremthru-proxy:latest
    container_name: stremthru-proxy
    ports:
      - "8888:8888"
    restart: unless-stopped
    environment:
        - STREMTHRU_PORT=8888
        - STREMTHRU_BASE_URL=http://localhost:8888
    healthcheck:
        test: ["CMD", "wget", "-qO-", "http://localhost:8888/v0/health"]
        interval: 30s
        timeout: 3s
        retries: 3
        start_period: 10s
