# https://github.com/Viren070/AIOStreams/blob/main/compose.yaml
services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    pull_policy: always
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    labels:
      - wud.watch.enable=true
      - wud.tag.include=^v\d+\.\d+\.\d+$$
      - wud.watch.digest=true
      - wud.link.template=https://github.com/Viren070/AIOStreams/releases/tag/v$${major}.$${minor}.$${patch}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/v1/status"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s

  # https://github.com/cmj2002/warp-docker/blob/main/docker-compose.yml
  warp:
    image: caomingjun/warp:latest
    container_name: warp
    restart: unless-stopped
    device_cgroup_rules:
      - "c 10:200 rwm"
    expose:
      - 1080
    environment:
      - WARP_SLEEP=5
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./warp:/var/lib/cloudflare-warp
    labels:
      - wud.watch.enable=true
      - wud.tag.include=latest
      - wud.watch.digest=true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -x 'socks5h://127.0.0.1:1080' -fsSL 'https://www.cloudflare.com/cdn-cgi/trace' | grep -qE 'warp=(plus|on)' || exit 1",
        ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 5s

  # WUD – daily check at 03:00 Amsterdam time, Docker trigger auto-update
  wud:
    image: getwud/wud:latest
    container_name: wud
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      TZ: Europe/Amsterdam

      # Web UI port
      WUD_SERVER_PORT: 3001

      # WATCHER: listen to local Docker engine and check daily at 03:00
      WUD_WATCHER_LOCAL_CRON: 0 3 * * *
      WUD_WATCHER_LOCAL_WATCHBYDEFAULT: false
      WUD_WATCHER_LOCAL_WATCHATSTART: true

      # TRIGGER: use standard Docker trigger
      # pull new image and restart the running container
      WUD_TRIGGER_DOCKER_0_MODE: pullandrestart
      # act only on containers with the watch label
      WUD_TRIGGER_DOCKER_0_FILTER_LABEL: wud.watch.enable=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./wud-store:/store
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      - wud.watch.enable=true
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/getwud/wud/releases/tag/$${major}.$${minor}.$${patch}
