# https://github.com/Viren070/AIOStreams/blob/main/compose.yaml
services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    labels:
      - wud.watch.enable=true           # allow wud to watch this service
    healthcheck:
      test: wget -qO- http://localhost:3000/api/v1/status
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s

# https://github.com/cmj2002/warp-docker/blob/main/docker-compose.yml
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 10:200 rwm'
    expose:
      - 1080
    environment:
      - WARP_SLEEP=5
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./warp:/var/lib/cloudflare-warp
    labels:
      - wud.watch.enable=true           # allow wud to watch this service
    healthcheck:
      test: curl -x "socks5h://127.0.0.1:1080" -fsSL "https://www.cloudflare.com/cdn-cgi/trace" | grep -qE "warp=(plus|on)" || exit 1
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 5s

  # wud – watches selected containers and auto-updates every night at 03:00 Amsterdam time
  wud:
    image: getwud/wud:latest
    container_name: wud
    restart: unless-stopped
    ports:
      - 3001:3000                 # optional web UI
    environment:
      - TZ=Europe/Amsterdam
      - WUD_TRIGGER_SCHEDULE=0 3 * * *           # nightly cron schedule
      - WUD_TRIGGER_DOCKER=pull-and-restart     # auto-pull & restart via socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./wud-store:/wud-store                 # persist wud database
