version: "3.9"

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg:latest
    container_name: zurg
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - /root/zurg-jellyfin/zurg/config.yml:/app/config.yml:ro
      - /root/zurg-jellyfin/zurg/data:/app/data

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    depends_on:
      - zurg
    volumes:
      - jellyfin-config:/config
      # Zurg mount (read-only)
      - /mnt/zurgmnt:/media/zurg:ro

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Madrid
      - PORT=5055
    ports:
      - "5055:5055"
    volumes:
      - /root/zurg-jellyfin/jellyseerr/config:/app/config

  # -------------------------------------------------
  #  SEERRBRIDGE (replaces blackhole)
  # -------------------------------------------------
  seerrbridge:
    image: ghcr.io/woahai321/seerrbridge:latest
    container_name: seerrbridge
    restart: unless-stopped
    depends_on:
      - jellyseerr
    ports:
      - "8777:8777"
    volumes:
      # env file mounted read-only
      - /root/zurg-jellyfin/seerrbridge/.env:/app/.env:ro
      - /root/zurg-jellyfin/seerrbridge/logs:/app/logs
      - /root/zurg-jellyfin/seerrbridge/data:/app/data
    command: >
      sh -c "cat /app/.env > /dev/null &&
             echo 'Starting SeerrBridge with mounted env' &&
             uvicorn main:app --host 0.0.0.0 --port 8777"

  # -------------------------------------------------
  #  BRIDGEBOARD (optional dashboard)
  # -------------------------------------------------
  bridgeboard:
    image: ghcr.io/woahai321/bridgeboard:latest
    container_name: bridgeboard
    restart: unless-stopped
    depends_on:
      - seerrbridge
    ports:
      - "3777:3777"
    environment:
      - SEERRBRIDGE_URL=http://seerrbridge:8777
      - SEERRBRIDGE_LOG_PATH=/logs/seerrbridge.log
    volumes:
      - /root/zurg-jellyfin/seerrbridge/logs:/logs
      - /root/zurg-jellyfin/seerrbridge/.env:/app/.env:ro

volumes:
  jellyfin-config:
