services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg:latest
    container_name: zurg
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - zurg-config:/app
      - zurg-data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9999 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000
    volumes:
      - rclone-config:/config/rclone
      - zurg-mount:/data:rshared
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    command: >-
      mount zurg: /data
      --config=/config/rclone/rclone.conf
      --allow-other
      --dir-cache-time=10s
      --buffer-size=0M
      --vfs-cache-mode=minimal
      --vfs-read-chunk-size=1M
      --vfs-read-chunk-size-limit=32M
      --vfs-read-ahead=128M
      --poll-interval=15s
      --bwlimit=off:100M
      --log-level=INFO
    depends_on:
      zurg:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "mount | grep -q ' on /data '"]
      interval: 30s
      timeout: 10s
      retries: 3

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - JELLYFIN_PublishedServerUrl=${SERVICE_URL_JELLYFIN}
    volumes:
      - jellyfin-config:/config
      - zurg-mount/__all__:/media:ro
    ports:
      - "8096:8096"
    depends_on:
      rclone:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8096 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 15

volumes:
  zurg-config:
  zurg-data:
  rclone-config:
  zurg-mount:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/zurg
  jellyfin-config:
