version: "3.9"

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg:latest
    container_name: zurg
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - /root/zurg-jellyfin/zurg/config.yml:/app/config.yml:ro
      - /root/zurg-jellyfin/zurg/data:/app/data

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    depends_on:
      - zurg
    volumes:
      - jellyfin-config:/config
      # Zurg mount (read-only)
      - /mnt/zurgmnt:/media/zurg:ro

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Madrid
      - PORT=5055
    ports:
      - "5055:5055"
    volumes:
      - /root/zurg-jellyfin/jellyseerr/config:/app/config

  blackhole:
    image: ghcr.io/westsurname/scripts/blackhole:latest
    container_name: blackhole
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - /root/zurg-jellyfin/blackhole/.env
    environment:
      - BLACKHOLE_BASE_WATCH_PATH=/mnt/symlinks
    volumes:
      - /mnt:/mnt:rshared
    depends_on:
      - zurg

  blackhole4k:
    image: ghcr.io/westsurname/scripts/blackhole:latest
    container_name: blackhole4k
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - /root/zurg-jellyfin/blackhole/.env.4k
    environment:
      - BLACKHOLE_BASE_WATCH_PATH=/mnt/symlinks
      - RADARR_HOST=http://radarr4k:7878
      - SONARR_HOST=http://sonarr4k:8989
    volumes:
      - /mnt:/mnt:rshared
    depends_on:
      - zurg

volumes:
  jellyfin-config:
