version: '3.9'

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg:latest
    container_name: zurg
    restart: unless-stopped
    ports:
      - '9999:9999'
    volumes:
      # Use the config file located in /root/zurg-jellyfin/config.yml
      - /root/zurg-jellyfin/zurg/config.yml:/app/config.yml:ro
      - ./data:/app/data
    # health check which will always pass due to auth conflicts
    healthcheck:
      test: ['CMD', 'true']
      interval: 30s
      timeout: 10s
      retries: 5

  # rclone sidecar that mounts the zurg remote under /mnt/zurg
  rclone-zurg:
    image: rclone/rclone:latest
    container_name: rclone-zurg
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - TZ=Europe/Madrid
    volumes:
      # mount only the *file* — keep the dir writable for rclone
      - type: bind
        source: /root/zurg-jellyfin/rclone/rclone.conf
        target: /config/rclone/rclone.conf
        read_only: true
        is_directory: false
        content: ""
      - /mnt/zurg:/mnt/zurg:rshared
    depends_on:
      - zurg
    command: >-
      mount zurg: /mnt/zurg
      --config /config/rclone/rclone.conf
      --dir-cache-time 10s
      --poll-interval 0
      --vfs-cache-mode full
      --allow-other
      --allow-non-empty
      --uid 1000
      --gid 1000

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - '8096:8096'
    depends_on:
      - zurg
      - rclone-zurg
    volumes:
      - jellyfin-config:/config
      - /mnt/zurg:/media/zurg:ro
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:8096']
      interval: 30s
      timeout: 10s
      retries: 15

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Madrid
      - PORT=5055
    ports:
      - '5055:5055'
    depends_on:
      - jellyfin
    volumes:
      - /root/zurg-jellyfin/jellyseerr/config:/app/config
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://127.0.0.1:5055/api/v1/status || exit 1']
      start_period: 20s
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  jellyfin-config: