version: '3.9'

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg:latest
    container_name: zurg
    restart: unless-stopped
    ports:
      - '9999:9999'
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./data:/app/data
    healthcheck:
      test: ['CMD', 'curl', '-fsS', 'http://localhost:9999/dav/version.txt']
      interval: 30s
      timeout: 10s
      retries: 5

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - '8096:8096'
    volumes:
      - jellyfin-config:/config
      - zurg-media:/media/zurg:ro
    depends_on:
      - zurg
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:8096']
      interval: 30s
      timeout: 10s
      retries: 15

volumes:
  jellyfin-config:
  zurg-media:
    driver: rclone
    driver_opts:
      remote: 'zurg:'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0
      dir_cache_time: 10s
