version: '3.9'

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg:latest
    container_name: zurg
    restart: unless-stopped
    ports:
      - '9999:9999'
    volumes:
      - /root/zurg-jellyfin/zurg/config.yml:/app/config.yml:ro
      - ./data:/app/data
    healthcheck:
      test: ['CMD', 'true']
      interval: 30s
      timeout: 10s
      retries: 5

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - '8096:8096'
    depends_on:
      - zurg
    volumes:
      - jellyfin-config:/config
      - zurgmnt:/media/zurg:ro
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:8096']
      interval: 30s
      timeout: 10s
      retries: 15

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Madrid
      - PORT=5055
    ports:
      - '5055:5055'
    depends_on:
      - jellyfin
    volumes:
      - /root/zurg-jellyfin/jellyseerr/config:/app/config
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://127.0.0.1:5055/api/v1/status || exit 1'
        ]
      start_period: 20s
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  jellyfin-config:
  zurgmnt:
    driver: rclone
    driver_opts:
      remote: zurg:
      config: /root/zurg-jellyfin/rclone/rclone.conf
      vfs_cache_mode: full
      allow_other: "true"
