version: '3.9'

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg:latest
    container_name: zurg
    restart: unless-stopped
    ports:
      - '9999:9999'
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./data:/app/data
    healthcheck:
      test: ['CMD-SHELL', 'curl -fsS http://$ZURG_USER:$ZURG_PASS@127.0.0.1:9999/dav/version.txt']
      interval: 30s
      timeout: 10s
      retries: 5

  # rclone sidecar that mounts the zurg remote under /mnt/zurg
  rclone-zurg:
    image: rclone/rclone:latest
    container_name: rclone-zurg
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /var/lib/rclone/config/rclone.conf:/config/rclone/rclone.conf:ro
      - /mnt/zurg:/mnt/zurg:rshared
    command: >-
      mount zurg: /mnt/zurg
      --config /config/rclone/rclone.conf
      --dir-cache-time 10s
      --poll-interval 0
      --vfs-cache-mode full
      --allow-other
      --allow-non-empty
      --uid 1000
      --gid 1000

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - '8096:8096'
    depends_on:
      - zurg
      - rclone-zurg
    volumes:
      - jellyfin-config:/config
      - /mnt/zurg:/media/zurg:ro
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:8096']
      interval: 30s
      timeout: 10s
      retries: 15

volumes:
  jellyfin-config:
